/**
 * Interface microcopy: every button, form label, validation message, and notice.
 * Each entry becomes an editable field in Maestro Admin under "טקסטי ממשק".
 * Read in components with c("ui.<key>") and in non-React code with ui("<key>").
 * Placeholders like {n} / {name} are replaced by the code (see fmt() in useContent).
 */

export interface UiGroup {
  prefix: string;
  id: string;
  label: string;
}

export const UI_GROUPS: UiGroup[] = [
  { prefix: "common.", id: "ui-common", label: "טקסטי ממשק — כללי" },
  { prefix: "err.", id: "ui-errors", label: "טקסטי ממשק — הודעות שגיאה" },
  { prefix: "nav.", id: "ui-nav", label: "טקסטי ממשק — ניווט וכותרת" },
  { prefix: "store.", id: "ui-store", label: "טקסטי ממשק — חנות" },
  { prefix: "library.", id: "ui-library", label: "טקסטי ממשק — ספרייה" },
  { prefix: "reader.", id: "ui-reader", label: "טקסטי ממשק — קורא" },
  { prefix: "checkout.", id: "ui-checkout", label: "טקסטי ממשק — תשלום" },
  { prefix: "auth.", id: "ui-auth", label: "טקסטי ממשק — התחברות" },
  { prefix: "support.", id: "ui-support", label: "טקסטי ממשק — תמיכה" },
  { prefix: "legal.", id: "ui-legal", label: "טקסטי ממשק — עמודים משפטיים" },
  { prefix: "dashboard.", id: "ui-dashboard", label: "טקסטי ממשק — לוח בקרה" },
];

/** key (without "ui.") → [Hebrew label for the admin, default text] */
export const UI: Record<string, [string, string]> = {
  // common
  "common.back": ["חזרה", "חזרה"],
  "common.retry": ["נסו שוב", "נסו שוב"],
  "common.optional": ["\"לא חובה\" ליד שדה", "(לא חובה)"],
  "common.sending": ["כפתור בזמן שליחה", "שולחים…"],
  "common.all": ["\"הכול\" (סינון)", "הכול"],
  "common.loading": ["טוענים", "טוענים…"],
  "common.errorTitle": ["כותרת שגיאת טעינה", "משהו לא הסתדר."],
  "common.errorLoad": ["טקסט שגיאת טעינה", "לא הצלחנו לטעון את התוכן. אפשר לנסות שוב."],
  "common.errorFixOne": ["סיכום שגיאות — שדה אחד", "יש שדה אחד שצריך תיקון:"],
  "common.errorFixMany": ["סיכום שגיאות — כמה שדות ({n} = מספר)", "יש {n} שדות שצריכים תיקון:"],
  "common.skipMain": ["קישור \"דלג לתוכן\"", "דלג לתוכן הראשי"],
  "common.skipNav": ["קישור \"דלג לניווט\"", "דלג לניווט"],
  "common.fullName": ["שדה שם מלא", "שם מלא"],
  "common.phone": ["שדה טלפון", "טלפון"],
  "common.phoneHint": ["רמז לשדה טלפון", "לדוגמה: 050-1234567"],
  "common.email": ["שדה אימייל", "אימייל"],
  // errors
  "err.name": ["שם חסר", "יש להזין שם מלא."],
  "err.phoneMissing": ["טלפון חסר", "יש להזין מספר טלפון."],
  "err.phoneBad": ["טלפון לא תקין", "יש להזין מספר טלפון ישראלי תקין."],
  "err.emailBad": ["אימייל לא תקין", "כתובת האימייל אינה תקינה."],
  "err.passwordShort": ["סיסמה קצרה", "הסיסמה חייבת להכיל לפחות 8 תווים."],
  "err.passwordMismatch": ["סיסמאות לא תואמות", "הסיסמאות אינן תואמות."],
  "err.couponInvalid": ["קופון לא תקין", "הקופון אינו תקין או שפג תוקפו."],
  "err.couponExpired": ["קופון פג תוקף", "תוקף הקופון פג."],
  // nav / header
  "nav.home": ["תפריט: בית", "בית"],
  "nav.store": ["תפריט: חנות", "חנות"],
  "nav.library": ["תפריט: הספרייה שלי", "הספרייה שלי"],
  "nav.admin": ["תפריט: ניהול", "ניהול"],
  "nav.account": ["תפריט: חשבון", "חשבון"],
  "nav.login": ["תפריט: התחברות", "התחברות"],
  "nav.logout": ["תפריט: התנתקות", "התנתקות"],
  "nav.cta": ["כפתור גישה מהיר", "קבלו גישה"],
  "nav.greeting": ["תחילית ברכה", "שלום"],
  // store
  "store.addToCart": ["כפתור הוספה לעגלה", "הוספה לעגלה"],
  "store.buyNow": ["כפתור קנייה מיידית", "קנו עכשיו"],
  "store.viewDetails": ["קישור לפרטי מוצר", "לפרטים נוספים"],
  "store.filterCategory": ["סינון: קטגוריה", "קטגוריה"],
  "store.filterType": ["סינון: סוג מוצר", "סוג מוצר"],
  "store.sortBy": ["מיון לפי", "מיון לפי"],
  "store.priceAsc": ["מיון: מחיר עולה", "מחיר: מהנמוך לגבוה"],
  "store.priceDesc": ["מיון: מחיר יורד", "מחיר: מהגבוה לנמוך"],
  "store.nameAsc": ["מיון: שם א-ת", "שם: א-ת"],
  "store.empty": ["חנות ריקה", "אין מוצרים להצגה כרגע."],
  "store.sale": ["תג מבצע", "מבצע"],
  "store.freeSample": ["כפתור דוגמה חינמית", "קריאת דוגמה"],
  // library
  "library.empty": ["ספרייה ריקה", "עדיין לא רכשתם ספרים."],
  "library.continueReading": ["כפתור המשך קריאה", "המשך קריאה"],
  "library.startReading": ["כפתור התחלת קריאה", "התחילו לקרוא"],
  "library.progress": ["התקדמות ({n}%)", "{n}% הושלמו"],
  "library.noProgress": ["ספר שלא נקרא", "טרם נקרא"],
  // reader
  "reader.toc": ["תוכן העניינים", "תוכן העניינים"],
  "reader.prevPage": ["כפתור עמוד קודם", "הקודם"],
  "reader.nextPage": ["כפתור עמוד הבא", "הבא"],
  "reader.backToLibrary": ["חזרה לספרייה", "חזרה לספרייה"],
  "reader.toLibrary": ["קישור לספרייה", "לספרייה"],
  "reader.fontSize": ["גודל גופן", "גודל גופן"],
  "reader.theme": ["ערכת צבעים", "ערכת צבעים"],
  "reader.themeLight": ["ערכה: בהירה", "בהירה"],
  "reader.themeDark": ["ערכה: ככה", "כהה"],
  "reader.themeSepia": ["ערכה: ספיה", "ספיה"],
  "reader.personalCopy": ["תווית עותק אישי", "עותק אישי מסומן"],
  "reader.contentNotReady": ["תוכן טרם הועלה", "התוכן טרם הועלה"],
  "reader.contentNotReadyBody": ["תיאור תוכן חסר", "לקובץ הקריאה עדיין לא הוצמד עותק דיגיטלי במערכת."],
  "reader.grantError": ["שגיאת קישור", "הקישור לתוכן לא אושר"],
  "reader.grantErrorBody": ["תיאור שגיאת קישור", "כל קריאה מקבלת קישור חד־פעמי משלה. אם הגישה שלך תקינה, ניסיון נוסף מנפיק קישור טרי."],
  "reader.retry": ["כפתור ניסיון נוסף", "ניסיון נוסף"],
  "reader.contactSupport": ["כפתור פנייה לתמיכה", "פנייה לתמיכה"],
  "reader.swipeHint": ["רמז החלקה", "החליקו משולי המסך או הקישו עליהם כדי להפוך דף"],
  "reader.completed": ["הושלמו", "הושלמו"],
  "reader.page": ["עמוד", "עמוד"],
  "reader.accessBlocked": ["גישה נחסמה", "הגישה ממכשיר זה נחסמה"],
  "reader.sessionExpired": ["תוקף פג", "ההתקשרות פגה"],
  "reader.cannotOpen": ["לא ניתן לפתוח", "לא ניתן לפתוח את הקובץ"],
  "reader.blockedBody": ["תיאור חסימה", "מנהל מערכת חסם את הקריאה מהמכשיר הזה."],
  "reader.expiredBody": ["תיאור פג תוקף", "לא הייתה פעילות במשך זמן ממושך, ולכן הקריאה נעצרה. ההתקדמות שלך נשמרה."],
  "reader.renewDevice": ["כפתור חידוש מכשיר", "נסה לרשום את המכשיר שוב"],
  "reader.continueReading": ["כפתור המשך קריאה", "המשך קריאה"],
  "reader.drmNotice": ["הודעת הגנה", "התוכן מוסתר להגנה על זכויות יוצירים."],
  "reader.drmReturn": ["חזרה לקריאה", "חזרו לחלון זה כדי להמשיך לקרוא."],
  // checkout
  "checkout.title": ["כותרת תשלום", "תשלום"],
  "checkout.summary": ["כותרת סיכום הזמנה", "סיכום הזמנה"],
  "checkout.couponLabel": ["שדה קופון", "קוד קופון"],
  "checkout.couponApply": ["כפתור החלת קופון", "החל"],
  "checkout.couponRemove": ["כפתור הסרת קופון", "הסר"],
  "checkout.total": ["סה\"כ לתשלום", "סה\"כ לתשלום"],
  "checkout.pay": ["כפתור תשלום", "תשלום מאובטח"],
  "checkout.processing": ["כפתור בעת תשלום", "מעבד תשלום…"],
  "checkout.success": ["הודעת הצלחה", "התשלום בוצע בהצלחה!"],
  "checkout.successBody": ["טקסט הצלחה", "הספרים מחכים לכם בספרייה."],
  "checkout.goToLibrary": ["כפתור מעבר לספרייה", "לספרייה שלי"],
  // auth
  "auth.loginTitle": ["כותרת התחברות", "התחברות"],
  "auth.registerTitle": ["כותרת הרשמה", "יצירת חשבון"],
  "auth.loginSubtitle": ["תיאור התחברות", "גש לספרייה ולהתקדמות הקריאה שלך."],
  "auth.registerSubtitle": ["תיאור הרשמה", "החשבון ישמש אותך לרכישה, לספרייה ולמעקב אחרי ההזמנות."],
  "auth.firstName": ["שדה שם פרטי", "שם פרטי"],
  "auth.lastName": ["שדה שם משפחה", "שם משפחה"],
  "auth.emailLabel": ["שדה אימייל", "אימייל"],
  "auth.passwordLabel": ["שדה סיסמה", "סיסמה"],
  "auth.forgotPassword": ["קישור שכחתי סיסמה", "שכחת סיסמה?"],
  "auth.noAccount": ["אין חשבון", "אין לכם חשבון?"],
  "auth.hasAccount": ["יש חשבון", "יש לכם חשבון?"],
  "auth.register": ["כפתור הרשמה", "יצירת חשבון"],
  "auth.login": ["כפתור התחברות", "התחברות"],
  "auth.logoutConfirm": ["אישור התנתקות", "האם להתנתק?"],
  "auth.createAccount": ["כפתור יצירת חשבון", "יצירת חשבון"],
  "auth.loggingIn": ["כפתור בעת התחברות", "מתחבר..."],
  "auth.creatingAccount": ["כפתור בעת הרשמה", "יוצר חשבון..."],
  "auth.noAccountLink": ["קישור צרו חשבון", "צרו חשבון חדש"],
  "auth.haveAccountLink": ["קישור התחברות", "התחברות"],
  "auth.guestCheckout": ["טקסט רכישה כאורח", "ניתן גם לרכוש ישירות מ־"],
  "auth.guestCheckoutStore": ["קישור חנות", "החנות"],
  "auth.guestCheckoutSuffix": ["המשך טקסט רכישה", "— החשבון ייווצר אוטומטית."],
  "auth.passwordHint": ["רמז סיסמה", "8 תווים לפחות, כולל אותיות וספרה אחת."],
  "auth.termsAgree": ["הסכמה לתנאים", "על ידי יצירת חשבון, אתה מסים ל"],
  "auth.termsLink": ["קישור תנאי שימוש", "תנאי השימוש"],
  "auth.termsSuffix": ["המשך טקסט תנאים", "שלנו."],
  // support
  "support.title": ["כותרת תמיכה", "תמיכה"],
  "support.submitTicket": ["כפתור שליחת פנייה", "שליחת הפנייה"],
  "support.sending": ["כפתור בעת שליחה", "שולח…"],
  "support.ticketNumber": ["תווית מספר פנייה", "מספר המעקב שלך:"],
  "support.fullName": ["שדה שם מלא", "שם מלא"],
  "support.emailLabel": ["שדה אימייל", "אימייל"],
  "support.phoneLabel": ["שדה טלפון", "טלפון (אופציונלי)"],
  "support.topicLabel": ["שדה נושא", "נושא הפנייה"],
  "support.orderLink": ["שדה שיוך הזמנה", "שיוך להזמנה (אופציונלי)"],
  "support.noOrder": ["ללא שיוך", "ללא שיוך"],
  "support.subjectLabel": ["שדה כותרת", "כותרת"],
  "support.messageLabel": ["שדה פירוט", "פירוט הפנייה"],
  "support.successTitle": ["הודעת הצלחה — כותרת", "הפנייה התקבלה"],
  "support.newTicket": ["כפתור פנייה נוספת", "פנייה נוספת"],
  "support.backToDashboard": ["חזרה ללוח האישי", "חזרה ללוח האישי"],
  "support.loginToTrack": ["התחברות למעקב", "התחברות למעקב"],
  "support.previousInquiries": ["כותרת פניות קודמות", "פניות קודמות"],
  "support.loginToSeeHistory": ["התחבר לראות היסטוריה", "התחבר כדי לראות את היסטוריית הפניות שלך ואת מספרי המעקב."],
  "support.noInquiries": ["אין פניות", "אין עדיין פניות בחשבון שלך."],
  "support.beforeContacting": ["כותרת לפני שפונים", "לפני שפונים"],
  "support.topicGeneral": ["נושא: כללי", "כללי"],
  "support.topicOrder": ["נושא: הזמנה", "הזמנה"],
  "support.topicRefund": ["נושא: החזר", "החזר"],
  "support.topicAccess": ["נושא: גישה", "גישה לספר"],
  "support.topicBilling": ["נושא: חיוב", "חיוב"],
  "support.topicTechnical": ["נושא: טכני", "בעיה טכנית"],
  // legal
  "legal.draft": ["הודעת \"טיוטה\"", "נוסח זה הוא טיוטת עבודה ועדיין לא עבר בדיקה משפטית."],
  "legal.updated": ["\"עודכן לאחרונה\"", "עודכן לאחרונה:"],
  "legal.toc": ["תוכן עניינים (נגישות)", "תוכן עניינים"],
  // dashboard
  "dashboard.welcome": ["תחילית ברכה", "ברוך שובך,"],
  "dashboard.booksCount": ["תווית ספרים", "ספרים ברשותכם"],
  "dashboard.avgProgress": ["תווית התקדמות", "התקדמות ממוצעת"],
  "dashboard.lastActivity": ["תווית פעילות אחרונה", "פעילות אחרונה"],
  "dashboard.continueReading": ["כותרת המשך קריאה", "המשיכו לקרוא"],
  "dashboard.viewLibrary": ["קישור לספרייה", "לצפייה בספרייה ←"],
  "dashboard.libraryEmpty": ["ספרייה ריקה", "הספרייה שלך ריקה."],
  "dashboard.browseStore": ["גלוש לחנות", "גלוש לחנות ←"],
  "dashboard.myLibrary": ["כותרת הספרייה", "הספרייה שלי"],
  "dashboard.myLibraryDesc": ["תיאור הספרייה", "כל הספרים שלך במקום אחד."],
  "dashboard.myStore": ["כותרת החנות", "החנות"],
  "dashboard.myStoreDesc": ["תיאור החנות", "גלה ספרים חדשים והרחב את הספרייה שלך."],
  "dashboard.devices": ["כותרת מכשירים", "מכשירים מחוברים"],
  "dashboard.devicesLimit": ["תיאור מגבלה", "הקריאה מוגבלת ל־"],
  "dashboard.devicesSimultaneous": ["יחידת מידה", "מכשירים בו־זמנית"],
  "dashboard.noDevices": ["אין מכשירים", "אין מכשירים רשומים. המכשיר הראשון יירשם אוטומטית כשתפתחו ספר לקריאה."],
  "dashboard.thisDevice": ["תווית מכשיר נוכחי", "המכשיר הזה"],
  "dashboard.releaseDevice": ["כפתור שחרור", "שחרור"],
  "dashboard.deviceReleased": ["הודעת שחרור", "המכשיר שוחרר והמקום התפנה במכסה."],
  "dashboard.capFull": ["מכסה מלאה", "המכסה מלאה. שחררו מכשיר שלא בשימוש כדי לפתוח ספר במכשיר חדש."],
  "dashboard.pageOf": ["עמוד מתוך", "עמוד {current} מתוך {total}"],
  "dashboard.pageOnly": ["עמוד בלבד", "עמוד {current}"],
  "dashboard.notStarted": ["טרם התחיל", "עוד לא התחלתם"],
  "dashboard.startReading": ["התחילו לקרוא", "התחילו לקרוא"],
  "dashboard.continueReadingBtn": ["המשך קריאה", "המשך קריאה"],
  "dashboard.today": ["היום", "היום"],
};
